# Generated by Django 3.1.6 on 2021-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='headspace',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(default='Okay', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prompt_response',
            field=models.CharField(max_length=1000),
        ),
    ]
