# Generated by Django 3.1.6 on 2021-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0003_auto_20210519_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(default='Okay', max_length=20),
        ),
    ]
