# Generated by Django 3.1.6 on 2021-05-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0006_auto_20210521_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
    ]
